Added fix for Issue 26 - code accounts for sha256 or checksum
dmikusa/binding-tool pull request #136
Opened 2024-03-05 01:43 UTC by dipalpat

The changes in this PR are related to issue 26 where some buildpack tomls don't use sha256 and instead use the checksum field.

2024-03-05 21:08 UTC, dmikusa requested changes
Thanks very much for the PR. Looks good, just a little feedback.

2024-03-05 21:08 UTC, dmikusa commented on src/deps.rs
> +            }
This doesn't quite work, because you're ignoring the first part of the split. This effectively treats all of the hashes like SHA256 hashes. 

The format is `<algo>:<hash>` and we would need to preserve the algorithm so it's known elsewhere. We can't just assume that `<algo>` will always be `sha256`.

There are two solutions for this:

1. We can fail if there's a different algorithm. So do a check here and panic if the checksum type is not `sha256`.
2. We can make a new type. So instead of sha256 being a String, we make a type like `Hash` which has fields `type` and `value`. The type of Dependency needs to change as well, so it takes a `Hash` and a URI. This is more work already, but we also would need to change the code that checks the hash so that it reads the algorithm and uses the correct algorithm to verify the hash.

I'm OK with either solution. 1.) is not ideal, but as far as I know we're using sha256 everywhere in Paketo, so it should work and be an improvement over what we're doing now. If you want to implement option 2.) that'd be great too. It's totally up to you.

2024-03-05 21:08 UTC, dmikusa commented on .vscode/settings.json
> +}
Please remove this file. I don't like having IDE files in the code base. If you want to add `.vscode/` to the `.gitignore` file that would be helpful too.

2024-03-05 21:08 UTC, dmikusa commented on src/deps.rs
> +    #[should_panic(expected = "sha256 or checksum field is required")]
I believe we're covering the case where the sha256 property is used, but I don't see test coverage for the case where `checksum` is used. Can you add coverage for that code path too?

2024-03-06 02:11 UTC, dipalpat commented on src/deps.rs
> +            }
For now, I went ahead and went ahead with 1st solution. I will add another PR when I have thought through 2nd solution in the near future.

2024-03-06 02:12 UTC, dipalpat commented on .vscode/settings.json
> +}
Yes, I did not mean to check-in. I went ahead and removed that and also added in .gitignore.

2024-03-06 02:13 UTC, dipalpat commented on src/deps.rs
> +    #[should_panic(expected = "sha256 or checksum field is required")]
I added couple test cases - 1. for checksum string check and 2. to check if algo in the hash is indeed sha256.

2024-03-11 15:34 UTC, dmikusa approved these changes
Thanks! Looks great.

2024-03-11 15:34 UTC, merged